name: paran_girin
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_screenutil: ^4.0.2+3
  http: ^0.12.2
  fluttertoast: ^7.1.6
  camera: ^0.5.8+5
  path_provider: ^1.6.14
  path: ^1.7.0
  gallery_saver: ^2.0.1
  lottie: ^0.7.0+1
  rive: ^0.6.7
  shared_preferences: ^0.5.12+4
  flutter_svg: ^0.19.1
  audioplayers:
  permission_handler: ^5.1.0
  cloud_firestore: ^0.16.0
  firebase_core: "^0.7.0"
  firebase_auth: "^0.20.0+1" 
  logger: ^0.9.4
  provider: ^3.1.0+1
  google_sign_in: ^4.0.11
  flutter_facebook_auth: ^2.0.1
  image_picker:
  firebase_storage:
  filesize: ^1.0.4
  flutter_uploader: ^1.2.1
  googleapis_auth: ^0.2.12+1
  video_compress: ^2.1.1
  flutter_downloader: ^1.5.2
  flutter_datetime_picker: ^1.5.0
  table_calendar: ^2.3.3
  intl:
  video_player:
  chewie:
  mailer:
  video_thumbnail: ^0.2.1
  sliding_up_panel:
  share: ^0.6.5+4
  rflutter_alert:
  circular_check_box:
  

dev_dependencies:
  flutter_test:
    sdk: flutter




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/avatars/data.json
      - assets/avatars/home.gif
      - assets/avatars/hi2.gif
      - assets/avatars/
      - assets/icons/
      - assets/icons/circle.svg
      - assets/icons/check-circle.svg
      - assets/icons/google.svg
      - assets/icons/facebook.svg
      - assets/images/
      - assets/background/
      - assets/videoEx/sample1.mp4
      - assets/videoEx/sample2.mp4
      - assets/videoEx/videoTest.mp4
      - assets/onboarding/onboard_0.gif
      - assets/onboarding/onboard_1.gif
      - assets/onboarding/onboard_2.gif
      - assets/onboarding/onboard_3.gif
      - assets/music/bgm.mp3
      - assets/popup/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

  fonts:
    - family: Noto Sans KR
      fonts:
        - asset: assets/fonts/NotoSansKR-Black.otf
          weight: 900
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSansKR-Light.otf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Regular.otf
        - asset: assets/fonts/NotoSansKR-Thin.otf
          weight: 100

      # Noto Sans CJK KR
      # fonts:
      #   - asset: assets/fonts/NotoSansCJKkr-Black.otf
      #     weight: 900
      #   - asset: assets/fonts/NotoSansCJKkr-Bold.otf
      #     weight: 700
      #   - asset: assets/fonts/NotoSansCJKkr-DemiLight.otf
      #     weight: 200
      #   - asset: assets/fonts/NotoSansCJKkr-Light.otf
      #     weight: 300
      #   - asset: assets/fonts/NotoSansCJKkr-Medium.otf
      #     weight: 500
      #   - asset: assets/fonts/NotoSansCJKkr-Regular.otf
      #   - asset: assets/fonts/NotoSansCJKkr-Thin.otf
      #     weight: 100